Shape Functions:
    Cylinder Functions:
        Barbell:
            - param:
                !YMLParameter
                name: bell_radius
                description: Spherical bell radius
                units: u"\u212B"
                value: 40
            - param:
                !YMLParameter
                name: radius
                description: Cylindrical bar radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: length
                description: Cylindrical bar radius
                units: u"\u212B"
                value: 400
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: sld
                description: Scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: solvent_sld
                description: Solvent scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 1
        Capped cylinder:
            - param:
                !YMLParameter
                name: radius
                description: Cylinder radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: cap_radius
                description: Cap radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: length
                description: Cylinder length
                units: u"\u212B"
                value: 400
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: sld
                description: Scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: solvent_sld
                description: Solvent scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 1
        Core shell cylinder:  
            - param:
                !YMLParameter
                name: radius
                description: Cylinder core radius
                units: u"\u00B0"
                value: 20
            - param:
                !YMLParameter
                name: thickness
                description: Cylinder shell thickness
                units: u"\u00B0"
                value: 20
            - param:
                !YMLParameter
                name: length
                description: Cylinder length
                units: u"\u00B0"
                value: 400
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: core_sld
                description: Cylinder core scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: shell_sld
                description: Cylinder shell scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: solvent_sld
                description: Solvent scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 1
        Cylinder:
            - param:
                !YMLParameter
                name: radius
                description: Cylinder radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: length
                description: Cylinder length
                units: u"\u212B"
                value: 400
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: core_sld
                description: Cylinder core scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: shell_sld
                description: Cylinder shell scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
    Ellipsoid Functions:
        Ellipsoid:
            - param:
                !YMLParameter
                name: rpolar
                description: Polar radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: requatorial
                description: Equatorial radius
                units: u"\u212B"
                value: 400
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: sld
                description: Ellipsoid scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: solvent_sld
                description: Solvent scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 1
        Triaxial ellipsoid:
            - param:
                !YMLParameter
                name: req_minor
                description: Minor equatorial radius
                units: u"\u212B"
                value: 20
            - param:
                !YMLParameter
                name: req_major 
                description: Equatorial radius
                units: u"\u212B"
                value: 400
            - param:
                !YMLParameter
                name: rpolar
                description: Polar radius
                units: u"\u212B"
                value: 10
            - param:
                !YMLParameter
                name: theta
                description: In plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: phi
                description: Out of plane angle (orientation)
                units: u"\u00B0"
                value: 60
            - param:
                !YMLParameter
                name: scale
                description: Source intensity
                units: None
                value: 1
            - param:
                !YMLParameter
                name: background
                description: Source background
                units: 1/cm
                value: 0
            - param:
                !YMLParameter
                name: sld
                description: Ellipsoid scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 4
            - param:
                !YMLParameter
                name: solvent_sld
                description: Solvent scattering len. density
                units: 1.0E-06 u"\u212B"-u"\u00B2"
                value: 1
